### ISSUE TITLE
Question: Why did you `ang` as a folder

### ISSUE THREAD

**Issue by twilson63** [peteplays/gol#3]
Just curious, why did you use `ang` as a folder for your application? I have never seen this as a standard, might be good to reference in the readme, the name of the folder since it is not a common standard like `public` or `www`

If it is a standard, please point me to the documentation, again it is good to include in your readme as dev's may not be aware of this kind of standard.

**Comment by peteplays** [comment]
I used ang because you mentioned that I maybe writing it again in jquery so I wanted to have different folders for each.


Peter Schnabel
Programmer
Jack Russell Software, A Tabula Rasa Healthcare Division
494 Wando Park Blvd, suite C
Mount Pleasant, SC  29464
Phone: 843-606-6484
Email: pschnabel@carekinesis.com
Web: http://www.tabularasahealthcare.com/
           http://www.carekinesis.com/
           http://www.jackhq.com<http://www.jackhq.com/>​

This e-mail may contain information that is confidential, privileged or otherwise protected from disclosure by the Health Insurance Portability and Accountability Act (HIPAA) and other state and federal laws.  This information is intended only for the individual names above.  Any review, use disclosure or dissemination of this material is strictly prohibited.  If you receive this information in error, please notify CareKinesis immediately at 888-974-2763 and delete the original at once.

**Comment by twilson63** [comment]
Cool, you may want to mention that in your `README.md` the big thing is to separate your game logic from presentation so that the presentation only has to change not rewrite the entire game.
